database:
    driverClass: org.postgresql.Driver
    user: unused-user
    password: unused-pw
    url: unused-url
  
server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 8080

logging:
    level: INFO
    loggers:
        com.csl456: DEBUG    
        org.hibernate.SQL: ALL
    
    appenders:
        - type: console