database:
    driverClass: org.postgresql.Driver
    user: bike_rental_user
    password: RiVerbit
    url: jdbc:postgresql://localhost:5432/bike_rental_db

server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 8080

logging:
    level: INFO
    loggers:
        com.csl456: DEBUG    
    
    appenders:
        - type: console