database:
    driverClass: org.postgresql.Driver
    url: $JDBC_DATABASE_URL
    user: $JDBC_DATABASE_USERNAME
    password: $JDBC_DATABASE_PASSWORD

server:
    type: simple
    applicationContextPath: /
    connector:
        type: http
        port: 8080

logging:
    level: INFO    
    appenders:
        - type: console